#ifndef KERNEL_INTERRUPT_NO_H
#define KERNEL_INTERRUPT_NO_H

#define INT_DIVIDE_ERROR 0
#define INT_DEBUG_EXCEPTION 1
#define INT_NMI 2
#define INT_BREAKPOINT 3
#define INT_OVERFLOW 4
#define INT_BOUND_RANGE_EXCEEDED 5
#define INT_INVALID_OPCODE 6
#define INT_DEVICE_NOT_AVAIL 7
#define INT_DOUBLE_FAULT 8
#define INT_COPROCESSOR_SEGMENT_OVERRUN 9
#define INT_INVALID_TSS 10
#define INT_SEGMENT_NOT_PRESENT 11
#define INT_STACK_FAULT 12
#define INT_GENERAL_PROTECTION 13
#define INT_PAGE_FAULT 14
#define INT_FLOATING_POINT_ERR 16
#define INT_ALIGNMENT_CHECK 17
#define INT_MACHINE_CHECK 18
#define INT_SIMD_FLOATING_POINT_EX 19
#define INT_VIRTUALIZATION 20
#define INT_CONTROL_PROTECTION 21

#endif
